~/docker/startBookStats.sh
export OPENSHIFT_PORT=3001
export OPENSHIFT_IP=127.0.0.1
export OPENSHIFT_POSTGRESQL_DB_USERNAME=bookstats
export OPENSHIFT_POSTGRESQL_DB_PASSWORD=bookstats_pwd
export OPENSHIFT_POSTGRESQL_DB_HOST=jef-i7
export OPENSHIFT_POSTGRESQL_DB_PORT=7000
npm start
